// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: metrics.proto

package collectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CounterAggregation int32

const (
	CounterAggregation_COUNTER_AGGREGATION_UNSPECIFIED CounterAggregation = 0
	CounterAggregation_COUNTER_AGGREGATION_SUM         CounterAggregation = 1
	CounterAggregation_COUNTER_AGGREGATION_RATE        CounterAggregation = 2
)

// Enum value maps for CounterAggregation.
var (
	CounterAggregation_name = map[int32]string{
		0: "COUNTER_AGGREGATION_UNSPECIFIED",
		1: "COUNTER_AGGREGATION_SUM",
		2: "COUNTER_AGGREGATION_RATE",
	}
	CounterAggregation_value = map[string]int32{
		"COUNTER_AGGREGATION_UNSPECIFIED": 0,
		"COUNTER_AGGREGATION_SUM":         1,
		"COUNTER_AGGREGATION_RATE":        2,
	}
)

func (x CounterAggregation) Enum() *CounterAggregation {
	p := new(CounterAggregation)
	*p = x
	return p
}

func (x CounterAggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CounterAggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (CounterAggregation) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x CounterAggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CounterAggregation.Descriptor instead.
func (CounterAggregation) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type GaugeAggregation int32

const (
	GaugeAggregation_GAUGE_AGGREGATION_UNSPECIFIED GaugeAggregation = 0
	GaugeAggregation_GAUGE_AGGREGATION_LAST        GaugeAggregation = 1
	GaugeAggregation_GAUGE_AGGREGATION_MIN         GaugeAggregation = 2
	GaugeAggregation_GAUGE_AGGREGATION_MAX         GaugeAggregation = 3
	GaugeAggregation_GAUGE_AGGREGATION_AVERAGE     GaugeAggregation = 4
)

// Enum value maps for GaugeAggregation.
var (
	GaugeAggregation_name = map[int32]string{
		0: "GAUGE_AGGREGATION_UNSPECIFIED",
		1: "GAUGE_AGGREGATION_LAST",
		2: "GAUGE_AGGREGATION_MIN",
		3: "GAUGE_AGGREGATION_MAX",
		4: "GAUGE_AGGREGATION_AVERAGE",
	}
	GaugeAggregation_value = map[string]int32{
		"GAUGE_AGGREGATION_UNSPECIFIED": 0,
		"GAUGE_AGGREGATION_LAST":        1,
		"GAUGE_AGGREGATION_MIN":         2,
		"GAUGE_AGGREGATION_MAX":         3,
		"GAUGE_AGGREGATION_AVERAGE":     4,
	}
)

func (x GaugeAggregation) Enum() *GaugeAggregation {
	p := new(GaugeAggregation)
	*p = x
	return p
}

func (x GaugeAggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GaugeAggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[1].Descriptor()
}

func (GaugeAggregation) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[1]
}

func (x GaugeAggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GaugeAggregation.Descriptor instead.
func (GaugeAggregation) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

type SampleAggregation int32

const (
	SampleAggregation_SAMPLE_AGGREGATION_UNSPECIFIED SampleAggregation = 0
	SampleAggregation_SAMPLE_AGGREGATION_COUNT       SampleAggregation = 1
	SampleAggregation_SAMPLE_AGGREGATION_SUM         SampleAggregation = 2
	SampleAggregation_SAMPLE_AGGREGATION_AVERAGE     SampleAggregation = 3
)

// Enum value maps for SampleAggregation.
var (
	SampleAggregation_name = map[int32]string{
		0: "SAMPLE_AGGREGATION_UNSPECIFIED",
		1: "SAMPLE_AGGREGATION_COUNT",
		2: "SAMPLE_AGGREGATION_SUM",
		3: "SAMPLE_AGGREGATION_AVERAGE",
	}
	SampleAggregation_value = map[string]int32{
		"SAMPLE_AGGREGATION_UNSPECIFIED": 0,
		"SAMPLE_AGGREGATION_COUNT":       1,
		"SAMPLE_AGGREGATION_SUM":         2,
		"SAMPLE_AGGREGATION_AVERAGE":     3,
	}
)

func (x SampleAggregation) Enum() *SampleAggregation {
	p := new(SampleAggregation)
	*p = x
	return p
}

func (x SampleAggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SampleAggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[2].Descriptor()
}

func (SampleAggregation) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[2]
}

func (x SampleAggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SampleAggregation.Descriptor instead.
func (SampleAggregation) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

type RecordMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *MetricRef             `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMetricRequest) Reset() {
	*x = RecordMetricRequest{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMetricRequest) ProtoMessage() {}

func (x *RecordMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMetricRequest.ProtoReflect.Descriptor instead.
func (*RecordMetricRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *RecordMetricRequest) GetMetric() *MetricRef {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *RecordMetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RecordMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMetricResponse) Reset() {
	*x = RecordMetricResponse{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMetricResponse) ProtoMessage() {}

func (x *RecordMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMetricResponse.ProtoReflect.Descriptor instead.
func (*RecordMetricResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

type RegisterMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Series        []*Series              `protobuf:"bytes,2,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMetricsRequest) Reset() {
	*x = RegisterMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMetricsRequest) ProtoMessage() {}

func (x *RegisterMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMetricsRequest.ProtoReflect.Descriptor instead.
func (*RegisterMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterMetricsRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *RegisterMetricsRequest) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type Series struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*Series_Counter
	//	*Series_Gauge
	//	*Series_Sample
	Config        isSeries_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *Series) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Series) GetConfig() isSeries_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Series) GetCounter() *CounterMetricConfig {
	if x != nil {
		if x, ok := x.Config.(*Series_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

func (x *Series) GetGauge() *GaugeMetricConfig {
	if x != nil {
		if x, ok := x.Config.(*Series_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *Series) GetSample() *SampleMetricConfig {
	if x != nil {
		if x, ok := x.Config.(*Series_Sample); ok {
			return x.Sample
		}
	}
	return nil
}

type isSeries_Config interface {
	isSeries_Config()
}

type Series_Counter struct {
	Counter *CounterMetricConfig `protobuf:"bytes,2,opt,name=counter,proto3,oneof"`
}

type Series_Gauge struct {
	Gauge *GaugeMetricConfig `protobuf:"bytes,3,opt,name=gauge,proto3,oneof"`
}

type Series_Sample struct {
	Sample *SampleMetricConfig `protobuf:"bytes,4,opt,name=sample,proto3,oneof"`
}

func (*Series_Counter) isSeries_Config() {}

func (*Series_Gauge) isSeries_Config() {}

func (*Series_Sample) isSeries_Config() {}

type RegisterMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMetricsResponse) Reset() {
	*x = RegisterMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMetricsResponse) ProtoMessage() {}

func (x *RegisterMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMetricsResponse.ProtoReflect.Descriptor instead.
func (*RegisterMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

type MetricRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Series        string                 `protobuf:"bytes,2,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRef) Reset() {
	*x = MetricRef{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRef) ProtoMessage() {}

func (x *MetricRef) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRef.ProtoReflect.Descriptor instead.
func (*MetricRef) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MetricRef) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *MetricRef) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

type CounterMetricConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggregations  []CounterAggregation   `protobuf:"varint,1,rep,packed,name=aggregations,proto3,enum=beaver.collector.v1.CounterAggregation" json:"aggregations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterMetricConfig) Reset() {
	*x = CounterMetricConfig{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterMetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterMetricConfig) ProtoMessage() {}

func (x *CounterMetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterMetricConfig.ProtoReflect.Descriptor instead.
func (*CounterMetricConfig) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *CounterMetricConfig) GetAggregations() []CounterAggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

type GaugeMetricConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggregations  []GaugeAggregation     `protobuf:"varint,1,rep,packed,name=aggregations,proto3,enum=beaver.collector.v1.GaugeAggregation" json:"aggregations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GaugeMetricConfig) Reset() {
	*x = GaugeMetricConfig{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaugeMetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaugeMetricConfig) ProtoMessage() {}

func (x *GaugeMetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaugeMetricConfig.ProtoReflect.Descriptor instead.
func (*GaugeMetricConfig) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *GaugeMetricConfig) GetAggregations() []GaugeAggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

type SampleMetricConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Aggregations []SampleAggregation    `protobuf:"varint,1,rep,packed,name=aggregations,proto3,enum=beaver.collector.v1.SampleAggregation" json:"aggregations,omitempty"`
	// Quantiles are expressed from 0.0 through 1.0. For example, 0.99 is p99.
	Quantiles     []float64 `protobuf:"fixed64,2,rep,packed,name=quantiles,proto3" json:"quantiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleMetricConfig) Reset() {
	*x = SampleMetricConfig{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleMetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMetricConfig) ProtoMessage() {}

func (x *SampleMetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMetricConfig.ProtoReflect.Descriptor instead.
func (*SampleMetricConfig) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *SampleMetricConfig) GetAggregations() []SampleAggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

func (x *SampleMetricConfig) GetQuantiles() []float64 {
	if x != nil {
		return x.Quantiles
	}
	return nil
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x13beaver.collector.v1\"c\n" +
	"\x13RecordMetricRequest\x126\n" +
	"\x06metric\x18\x01 \x01(\v2\x1e.beaver.collector.v1.MetricRefR\x06metric\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x16\n" +
	"\x14RecordMetricResponse\"e\n" +
	"\x16RegisterMetricsRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x123\n" +
	"\x06series\x18\x02 \x03(\v2\x1b.beaver.collector.v1.SeriesR\x06series\"\xef\x01\n" +
	"\x06Series\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\acounter\x18\x02 \x01(\v2(.beaver.collector.v1.CounterMetricConfigH\x00R\acounter\x12>\n" +
	"\x05gauge\x18\x03 \x01(\v2&.beaver.collector.v1.GaugeMetricConfigH\x00R\x05gauge\x12A\n" +
	"\x06sample\x18\x04 \x01(\v2'.beaver.collector.v1.SampleMetricConfigH\x00R\x06sampleB\b\n" +
	"\x06config\"\x19\n" +
	"\x17RegisterMetricsResponse\";\n" +
	"\tMetricRef\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x16\n" +
	"\x06series\x18\x02 \x01(\tR\x06series\"b\n" +
	"\x13CounterMetricConfig\x12K\n" +
	"\faggregations\x18\x01 \x03(\x0e2'.beaver.collector.v1.CounterAggregationR\faggregations\"^\n" +
	"\x11GaugeMetricConfig\x12I\n" +
	"\faggregations\x18\x01 \x03(\x0e2%.beaver.collector.v1.GaugeAggregationR\faggregations\"~\n" +
	"\x12SampleMetricConfig\x12J\n" +
	"\faggregations\x18\x01 \x03(\x0e2&.beaver.collector.v1.SampleAggregationR\faggregations\x12\x1c\n" +
	"\tquantiles\x18\x02 \x03(\x01R\tquantiles*t\n" +
	"\x12CounterAggregation\x12#\n" +
	"\x1fCOUNTER_AGGREGATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COUNTER_AGGREGATION_SUM\x10\x01\x12\x1c\n" +
	"\x18COUNTER_AGGREGATION_RATE\x10\x02*\xa6\x01\n" +
	"\x10GaugeAggregation\x12!\n" +
	"\x1dGAUGE_AGGREGATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16GAUGE_AGGREGATION_LAST\x10\x01\x12\x19\n" +
	"\x15GAUGE_AGGREGATION_MIN\x10\x02\x12\x19\n" +
	"\x15GAUGE_AGGREGATION_MAX\x10\x03\x12\x1d\n" +
	"\x19GAUGE_AGGREGATION_AVERAGE\x10\x04*\x91\x01\n" +
	"\x11SampleAggregation\x12\"\n" +
	"\x1eSAMPLE_AGGREGATION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SAMPLE_AGGREGATION_COUNT\x10\x01\x12\x1a\n" +
	"\x16SAMPLE_AGGREGATION_SUM\x10\x02\x12\x1e\n" +
	"\x1aSAMPLE_AGGREGATION_AVERAGE\x10\x032\xe5\x01\n" +
	"\x10MetricsCollector\x12c\n" +
	"\fRecordMetric\x12(.beaver.collector.v1.RecordMetricRequest\x1a).beaver.collector.v1.RecordMetricResponse\x12l\n" +
	"\x0fRegisterMetrics\x12+.beaver.collector.v1.RegisterMetricsRequest\x1a,.beaver.collector.v1.RegisterMetricsResponseB8Z6github.com/JKang025/beaver/proto/collector;collectorpbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_metrics_proto_goTypes = []any{
	(CounterAggregation)(0),         // 0: beaver.collector.v1.CounterAggregation
	(GaugeAggregation)(0),           // 1: beaver.collector.v1.GaugeAggregation
	(SampleAggregation)(0),          // 2: beaver.collector.v1.SampleAggregation
	(*RecordMetricRequest)(nil),     // 3: beaver.collector.v1.RecordMetricRequest
	(*RecordMetricResponse)(nil),    // 4: beaver.collector.v1.RecordMetricResponse
	(*RegisterMetricsRequest)(nil),  // 5: beaver.collector.v1.RegisterMetricsRequest
	(*Series)(nil),                  // 6: beaver.collector.v1.Series
	(*RegisterMetricsResponse)(nil), // 7: beaver.collector.v1.RegisterMetricsResponse
	(*MetricRef)(nil),               // 8: beaver.collector.v1.MetricRef
	(*CounterMetricConfig)(nil),     // 9: beaver.collector.v1.CounterMetricConfig
	(*GaugeMetricConfig)(nil),       // 10: beaver.collector.v1.GaugeMetricConfig
	(*SampleMetricConfig)(nil),      // 11: beaver.collector.v1.SampleMetricConfig
}
var file_metrics_proto_depIdxs = []int32{
	8,  // 0: beaver.collector.v1.RecordMetricRequest.metric:type_name -> beaver.collector.v1.MetricRef
	6,  // 1: beaver.collector.v1.RegisterMetricsRequest.series:type_name -> beaver.collector.v1.Series
	9,  // 2: beaver.collector.v1.Series.counter:type_name -> beaver.collector.v1.CounterMetricConfig
	10, // 3: beaver.collector.v1.Series.gauge:type_name -> beaver.collector.v1.GaugeMetricConfig
	11, // 4: beaver.collector.v1.Series.sample:type_name -> beaver.collector.v1.SampleMetricConfig
	0,  // 5: beaver.collector.v1.CounterMetricConfig.aggregations:type_name -> beaver.collector.v1.CounterAggregation
	1,  // 6: beaver.collector.v1.GaugeMetricConfig.aggregations:type_name -> beaver.collector.v1.GaugeAggregation
	2,  // 7: beaver.collector.v1.SampleMetricConfig.aggregations:type_name -> beaver.collector.v1.SampleAggregation
	3,  // 8: beaver.collector.v1.MetricsCollector.RecordMetric:input_type -> beaver.collector.v1.RecordMetricRequest
	5,  // 9: beaver.collector.v1.MetricsCollector.RegisterMetrics:input_type -> beaver.collector.v1.RegisterMetricsRequest
	4,  // 10: beaver.collector.v1.MetricsCollector.RecordMetric:output_type -> beaver.collector.v1.RecordMetricResponse
	7,  // 11: beaver.collector.v1.MetricsCollector.RegisterMetrics:output_type -> beaver.collector.v1.RegisterMetricsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_metrics_proto_msgTypes[3].OneofWrappers = []any{
		(*Series_Counter)(nil),
		(*Series_Gauge)(nil),
		(*Series_Sample)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
