// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: metrics.proto

package collectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsCollector_CountMetric_FullMethodName     = "/beaver.collector.v1.MetricsCollector/CountMetric"
	MetricsCollector_RecordMetric_FullMethodName    = "/beaver.collector.v1.MetricsCollector/RecordMetric"
	MetricsCollector_RegisterMetrics_FullMethodName = "/beaver.collector.v1.MetricsCollector/RegisterMetrics"
)

// MetricsCollectorClient is the client API for MetricsCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsCollectorClient interface {
	CountMetric(ctx context.Context, in *CountMetricRequest, opts ...grpc.CallOption) (*CountMetricResponse, error)
	RecordMetric(ctx context.Context, in *RecordMetricRequest, opts ...grpc.CallOption) (*RecordMetricResponse, error)
	RegisterMetrics(ctx context.Context, in *RegisterMetricsRequest, opts ...grpc.CallOption) (*RegisterMetricsResponse, error)
}

type metricsCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsCollectorClient(cc grpc.ClientConnInterface) MetricsCollectorClient {
	return &metricsCollectorClient{cc}
}

func (c *metricsCollectorClient) CountMetric(ctx context.Context, in *CountMetricRequest, opts ...grpc.CallOption) (*CountMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountMetricResponse)
	err := c.cc.Invoke(ctx, MetricsCollector_CountMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsCollectorClient) RecordMetric(ctx context.Context, in *RecordMetricRequest, opts ...grpc.CallOption) (*RecordMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordMetricResponse)
	err := c.cc.Invoke(ctx, MetricsCollector_RecordMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsCollectorClient) RegisterMetrics(ctx context.Context, in *RegisterMetricsRequest, opts ...grpc.CallOption) (*RegisterMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsCollector_RegisterMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsCollectorServer is the server API for MetricsCollector service.
// All implementations must embed UnimplementedMetricsCollectorServer
// for forward compatibility.
type MetricsCollectorServer interface {
	CountMetric(context.Context, *CountMetricRequest) (*CountMetricResponse, error)
	RecordMetric(context.Context, *RecordMetricRequest) (*RecordMetricResponse, error)
	RegisterMetrics(context.Context, *RegisterMetricsRequest) (*RegisterMetricsResponse, error)
	mustEmbedUnimplementedMetricsCollectorServer()
}

// UnimplementedMetricsCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsCollectorServer struct{}

func (UnimplementedMetricsCollectorServer) CountMetric(context.Context, *CountMetricRequest) (*CountMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountMetric not implemented")
}
func (UnimplementedMetricsCollectorServer) RecordMetric(context.Context, *RecordMetricRequest) (*RecordMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMetric not implemented")
}
func (UnimplementedMetricsCollectorServer) RegisterMetrics(context.Context, *RegisterMetricsRequest) (*RegisterMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMetrics not implemented")
}
func (UnimplementedMetricsCollectorServer) mustEmbedUnimplementedMetricsCollectorServer() {}
func (UnimplementedMetricsCollectorServer) testEmbeddedByValue()                          {}

// UnsafeMetricsCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsCollectorServer will
// result in compilation errors.
type UnsafeMetricsCollectorServer interface {
	mustEmbedUnimplementedMetricsCollectorServer()
}

func RegisterMetricsCollectorServer(s grpc.ServiceRegistrar, srv MetricsCollectorServer) {
	// If the following call panics, it indicates UnimplementedMetricsCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsCollector_ServiceDesc, srv)
}

func _MetricsCollector_CountMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServer).CountMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollector_CountMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServer).CountMetric(ctx, req.(*CountMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsCollector_RecordMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServer).RecordMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollector_RecordMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServer).RecordMetric(ctx, req.(*RecordMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsCollector_RegisterMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServer).RegisterMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollector_RegisterMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServer).RegisterMetrics(ctx, req.(*RegisterMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsCollector_ServiceDesc is the grpc.ServiceDesc for MetricsCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beaver.collector.v1.MetricsCollector",
	HandlerType: (*MetricsCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountMetric",
			Handler:    _MetricsCollector_CountMetric_Handler,
		},
		{
			MethodName: "RecordMetric",
			Handler:    _MetricsCollector_RecordMetric_Handler,
		},
		{
			MethodName: "RegisterMetrics",
			Handler:    _MetricsCollector_RegisterMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
